name: CVE Scanning

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'js/**'
      - '.github/node-cve-ignore-list.xml'
      - '**/package.json'
      - '**/yarn.lock'
      - '.github/workflows/cve-scanning.yml'

jobs:
  node-scan:
    name: ${{ matrix.module-folder }}-node-scan
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
        matrix:
          module-folder: ['js']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build project with NPM
        run: yarn install --production --frozen-lockfile
        working-directory: ${{ matrix.module-folder }}
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@3102a65fd5f36d0000297576acc56a475b0de98d
        id: Depcheck
        with:
          project: '${{ matrix.module-folder }}'
          path: '${{ matrix.module-folder }}'
          format: 'HTML'
          out: '${{ matrix.module-folder }}-reports'
          args: >
            --suppression .github/node-cve-ignore-list.xml
            --nodeAuditSkipDevDependencies
            --nodePackageSkipDevDependencies
            --failOnCVSS 6
            --enableRetired
      - name: Upload Test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/${{ matrix.module-folder }}-reports